# Generated by Django 4.0.5 on 2022-07-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="social_media_platoform",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaign.socialmediaplatform",
            ),
        ),
    ]
